# Generated by Django 2.2.20 on 2021-05-11 20:35
from datetime import timedelta

import django.core.validators
from django.db import migrations, models
import exchange.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blockfarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='duration',
            field=models.DurationField(default=timedelta()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='total_staked',
            field=exchange.fields.FixedDecimalField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='user_staked',
            field=exchange.fields.FixedDecimalField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'Stake'), (1, 'Unstake')]),
        ),
    ]
