# Generated by Django 2.2.20 on 2021-05-20 12:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import exchange.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchange', '0080_currency_currency_scale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Deposit account'), (1, 'Reward account')])),
                ('balance', exchange.fields.FixedDecimalField(default=0.0, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('treasury_id', models.IntegerField(null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exchange.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('begin_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('hard_cap', exchange.fields.FixedDecimalField(default=0.0)),
                ('rate', exchange.fields.FixedDecimalField(default=0.0)),
                ('is_enable', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('deposit_currency', models.ManyToManyField(to='exchange.Currency')),
                ('reward_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exchange.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Deposit wallet'), (1, 'Reward wallet')])),
                ('balance', exchange.fields.FixedDecimalField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockfunder.Program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', exchange.fields.FixedDecimalField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=0)),
                ('rewarded', models.BooleanField(default=False)),
                ('deposit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TRANSACTION_deposit_account', to='blockfunder.Account')),
                ('deposit_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exchange.Currency')),
                ('deposit_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TRANSACTION_deposit_wallet', to='blockfunder.Wallet')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockfunder.Program')),
                ('reward_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TRANSACTION_reward_account', to='blockfunder.Account')),
                ('reward_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TRANSACTION_reward_wallet', to='blockfunder.Wallet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockfunder.Program'),
        ),
    ]
