# Generated by Django 2.2.20 on 2021-05-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfunder', '0002_auto_20210521_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(max_length=64),
        ),
    ]
