# Generated by Django 2.2.20 on 2021-05-22 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0008_auto_20210521_1757'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockfunder', '0003_auto_20210521_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseAgreement',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('text', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='affiliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='affiliate.Program'),
        ),
        migrations.CreateModel(
            name='LicenseAgreementConfirmation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockfunder.LicenseAgreement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='agreement',
            field=models.ManyToManyField(blank=True, to='blockfunder.LicenseAgreement'),
        ),
        migrations.AddConstraint(
            model_name='licenseagreementconfirmation',
            constraint=models.UniqueConstraint(fields=('user', 'license'), name='unique_user_license'),
        ),
    ]
