# Generated by Django 2.2.20 on 2021-05-24 11:33

from decimal import Decimal
from django.db import migrations, models
import exchange.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blockfunder', '0004_auto_20210522_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total',
            field=exchange.fields.FixedDecimalField(default=Decimal('0')),
        ),
        migrations.AlterField(
            model_name='licenseagreement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='licenseagreementconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
