# Generated by Django 2.2.20 on 2021-05-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfunder', '0005_auto_20210524_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseagreementconfirmation',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
        migrations.AddField(
            model_name='licenseagreementconfirmation',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='licenseagreement',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='licenseagreementconfirmation',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
