# Generated by Django 2.2.20 on 2021-05-26 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blockfunder', '0007_auto_20210525_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseagreement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='licenseagreementconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
