# Generated by Django 2.2.23 on 2021-06-01 17:40

import django.core.validators
from django.db import migrations
import exchange.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blockfunder', '0009_program_affiliate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount2',
            field=exchange.fields.FixedDecimalField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
