# Generated by Django 2.2.23 on 2021-06-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockfunder', '0010_transaction_amount2'),
        ('blockfunder', '0008_auto_20210526_1837'),
    ]

    operations = [
    ]
