# Generated by Django 2.2.23 on 2021-06-03 13:10

from django.db import migrations
import exchange.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blockfunder', '0011_merge_20210601_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rate',
            field=exchange.fields.FixedDecimalField(null=True),
        ),
    ]
